//
// Created by wuviv on 2020-12-06.
//

#ifndef DESIGN_PATTERNS_APPLICATIONCONFIGURATOR_HPP
#define DESIGN_PATTERNS_APPLICATIONCONFIGURATOR_HPP


class ApplicationConfigurator {

};


#endif //DESIGN_PATTERNS_APPLICATIONCONFIGURATOR_HPP
